install! 'cocoapods',
  :disable_input_output_paths => true

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'ComposeAppCocoaPod', :path => '../ios-kit'
#   pod 'AppSharedCocoaPod', :path => '../shared'
end
