name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-overwrite-existing: true
      - name: Build
        run: ./gradlew build
