name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-overwrite-existing: true
      - name: Cache build directories
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            **/build
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/*.gradle*','**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-
      - name: Build
        run: ./gradlew build
      - name: Archive build-output artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-build-artifacts
          path: |
            build/reports/problems
            shared/build/reports
            composeApp/build/reports
